# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bed4b44a5d8df1c3f11b7f6c97d3c7777b44486f8d27e4c2a2d648522f521be44fa3df2ae9d529b0a724f0112e6e482eb83ce08924a16d218b3e073a359ec7a5

test:
  secret_key_base: 7ef46caf9d7944dc006757699b7ceedbbd33598ba375caea1a369a0883b5eea110ec947b36151e2ce4f59d187a527aa46883e679c3b3b281f55f40d0d819cd2b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
